/**
 * Build-time skin fetcher: downloads the whale-fantasy skin assets
 * (skin.css + patches.css, v2 manifest) from the dsh-web market tree and
 * bakes them into src/client/generated/skin-assets.ts so the plugin is
 * fully self-contained — CSS and video both inline, no runtime CDN.
 *
 * The background video is assets/whale-blink-loop.mp4: the upstream
 * 25.5 s loop trimmed to the 2.58 s blink segment (frames 378-439,
 * 15.71 s-18.29 s; the line-construction intro is dropped). Reproduce with:
 *   ffmpeg -ss 15.7083 -i whale-fantasy-loop.mp4 -frames:v 62 \
 *     -c:v libx264 -crf 19 -preset slow -pix_fmt yuv420p -an \
 *     -movflags +faststart assets/whale-blink-loop.mp4
 *
 * Re-run with `pnpm fetch-skin` to pick up upstream skin updates.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const REF = 'dev'
const BASE = `https://raw.githubusercontent.com/zhu1090093659/dsh-web/${REF}/market/dist/assets/skins/whale-fantasy`

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = resolve(ROOT, 'src/client/generated/skin-assets.ts')
const VIDEO = resolve(ROOT, 'assets/whale-blink-loop.mp4')

async function fetchText(path) {
  const response = await fetch(`${BASE}/${path}`)
  if (!response.ok) throw new Error(`fetch ${path}: HTTP ${response.status}`)
  return await response.text()
}

const [skinCss, patchesCss, license, video] = await Promise.all([
  fetchText('skin.css'),
  fetchText('patches.css'),
  fetchText('LICENSE'),
  readFile(VIDEO),
])

await mkdir(dirname(OUT), { recursive: true })
await writeFile(OUT, [
  '// Generated by scripts/fetch-skin.mjs. Do not edit — re-run `pnpm fetch-skin`.',
  `export const SKIN_CSS = ${JSON.stringify(skinCss)}`,
  `export const PATCHES_CSS = ${JSON.stringify(patchesCss)}`,
  `export const VIDEO_BASE64 = ${JSON.stringify(video.toString('base64'))}`,
  `export const SCRIM = ${JSON.stringify(
    'linear-gradient(180deg, rgba(5,7,13,0) 0%, rgba(5,7,13,0) 86%, rgba(5,7,13,0.16) 96%, rgba(5,7,13,0.22) 100%)',
  )}`,
  '',
].join('\n'))
await writeFile(resolve(ROOT, 'LICENSE'), license)

console.log(`skin-assets.ts written (skin.css ${skinCss.length} B, patches.css ${patchesCss.length} B, video ${video.length} B); LICENSE updated`)
