/**
 * Build-time skin fetcher: downloads the whale-fantasy skin assets
 * (skin.css + patches.css, v2 manifest) from the dsh-web market tree and
 * bakes them into src/client/generated/skin-assets.ts so the plugin is
 * fully self-contained for CSS. The background video is NOT inlined
 * (6.6 MB) — the client streams it from a CDN URL at runtime.
 *
 * Re-run with `pnpm fetch-skin` to pick up upstream skin updates.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const REF = 'dev'
const BASE = `https://raw.githubusercontent.com/zhu1090093659/dsh-web/${REF}/market/dist/assets/skins/whale-fantasy`
/** jsDelivr mirrors the same repo path; video streams from here at runtime. */
const CDN_BASE = `https://cdn.jsdelivr.net/gh/zhu1090093659/dsh-web@${REF}/market/dist/assets/skins/whale-fantasy`

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = resolve(ROOT, 'src/client/generated/skin-assets.ts')

async function fetchText(path) {
  const response = await fetch(`${BASE}/${path}`)
  if (!response.ok) throw new Error(`fetch ${path}: HTTP ${response.status}`)
  return await response.text()
}

const [skinCss, patchesCss, license] = await Promise.all([
  fetchText('skin.css'),
  fetchText('patches.css'),
  fetchText('LICENSE'),
])

await mkdir(dirname(OUT), { recursive: true })
await writeFile(OUT, [
  '// Generated by scripts/fetch-skin.mjs. Do not edit — re-run `pnpm fetch-skin`.',
  `export const SKIN_CSS = ${JSON.stringify(skinCss)}`,
  `export const PATCHES_CSS = ${JSON.stringify(patchesCss)}`,
  `export const VIDEO_URLS = ${JSON.stringify([
    `${CDN_BASE}/assets/whale-fantasy-loop.mp4`,
    `${BASE}/assets/whale-fantasy-loop.mp4`,
  ])} as const`,
  `export const SCRIM = ${JSON.stringify(
    'linear-gradient(180deg, rgba(5,7,13,0) 0%, rgba(5,7,13,0) 86%, rgba(5,7,13,0.16) 96%, rgba(5,7,13,0.22) 100%)',
  )}`,
  '',
].join('\n'))
await writeFile(resolve(ROOT, 'LICENSE'), license)

console.log(`skin-assets.ts written (skin.css ${skinCss.length} B, patches.css ${patchesCss.length} B); LICENSE updated`)
